In [14]:
from github import Github

# Authentication is defined via github.Auth
from github import Auth
import pandas as pd
import os

In [15]:
department = 'BLC'
private_token = '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'
host = "https://github.com"

In [16]:
auth = Auth.Token(private_token)
g = Github(auth=auth)
g.get_user().login

'kongyb1032002'

In [17]:
info_folder = os.path.join('info', department)
os.makedirs(info_folder, exist_ok=True)  # Tạo thư mục nếu chưa tồn tại

In [18]:
# 1. Lấy danh sách repositories mà người dùng sở hữu
user = g.get_user()
repos = user.get_repos()

In [19]:
list_repos = []
for repo in repos:
    list_repos.append({
        'id': repo.id,
        'name': repo.name,
        'full_name': repo.full_name,
        'owner': repo.owner.login,
        'created_at': repo.created_at,
        'default_branch': repo.default_branch,
    })

df_repos = pd.DataFrame(list_repos)

df_repos

,id,name,full_name,owner,created_at,default_branch
0,863839707,corev4-explorer,blcvn/corev4-explorer,blcvn,2024-09-27 02:32:19+00:00,main
1,884031925,lab-gitlab-api,blcvn/lab-gitlab-api,blcvn,2024-11-06 02:29:58+00:00,main
2,856157805,CYB-Database,DXL64/CYB-Database,DXL64,2024-09-12 05:03:06+00:00,main
3,856975972,CYB-Manager,DXL64/CYB-Manager,DXL64,2024-09-13 15:06:48+00:00,main
4,877679995,Ansible_example,kongyb1032002/Ansible_example,kongyb1032002,2024-10-24 03:58:45+00:00,main
5,881313813,docker-database,kongyb1032002/docker-database,kongyb1032002,2024-10-31 10:24:36+00:00,main
6,881830578,GoEthExamp,kongyb1032002/GoEthExamp,kongyb1032002,2024-11-01 10:29:26+00:00,main
7,828058053,go_microservice,kongyb1032002/go_microservice,kongyb1032002,2024-07-13 02:25:09+00:00,main
8,876959666,HAM-Tracking-Tool,kongyb1032002/HAM-Tracking-Tool,kongyb1032002,2024-10-22 21:00:12+00:00,main
9,883549550,Hyperledger-fabric,kongyb1032002/Hyperledger-fabric,kongyb1032002,2024-11-05 06:52:03+00:00,main
10,884114251,hyperledger-subscriber,kongyb1032002/hyperledger-subscriber,kongyb1032002,2024-11-06 06:58:56+00:00,main
11,364278416,L12SQ,kongyb1032002/L12SQ,kongyb1032002,2021-05-04 14:12:13+00:00,main
12,885233028,lab-api-gitlab,kongyb1032002/lab-api-gitlab,kongyb1032002,2024-11-08 07:59:57+00:00,main
13,884933459,mmo-frontend,kongyb1032002/mmo-frontend,kongyb1032002,2024-11-07 16:41:32+00:00,main
14,813429662,NuxtBase,kongyb1032002/NuxtBase,kongyb1032002,2024-06-11 04:27:16+00:00,main
15,816170293,Solidity,kongyb1032002/Solidity,kongyb1032002,2024-06-17 07:18:37+00:00,main
16,879641696,VNPAY-Go-Example,kongyb1032002/VNPAY-Go-Example,kongyb1032002,2024-10-28 09:39:46+00:00,main
17,819191371,logos-gpt,trananhhh/logos-gpt,trananhhh,2024-06-24 02:43:40+00:00,main

In [20]:
file_repos = os.path.join(info_folder, 'repos.csv')
df_repos.to_csv(file_repos, index=False)

In [21]:
orgs = user.get_orgs()
list_orgs = []
for org in orgs:
    list_orgs.append({
        'id': org.id,
        'name': org.login,
        'full_name': org.name,
        'created_at': org.created_at,
    })

df_orgs = pd.DataFrame(list_orgs)
df_orgs

          id         name full_name                created_at
0  129816109  blc-onchain      None 2023-04-04 02:49:34+00:00

In [22]:
file_orgs = os.path.join(info_folder, 'orgs.csv')
df_orgs.to_csv(file_orgs, index=False)

In [23]:
list_team_members = []

for org in orgs:
    teams = org.get_teams()
    for team in teams:
        members = team.get_members()
        for member in members:
            list_team_members.append({
                'org_name': org.login,
                'team_id': team.id,
                'team_name': team.name,
                'member_id': member.id,
                'member_login': member.login,
                'member_name': member.name,
                'created_at': member.created_at,
            })

df_team_members = pd.DataFrame(list_team_members)
df_team_members

Empty DataFrame
Columns: []
Index: []

In [24]:
file_team_members = os.path.join(info_folder, 'team_members.csv')
df_team_members.to_csv(file_team_members, index=False)

In [31]:
list_repo_members = []

for repo in repos:
    try:
        collaborators = repo.get_collaborators()  # Lấy tất cả các cộng tác viên của repo
        for collaborator in collaborators:
            print(collaborator)
            list_repo_members.append({
                'repo_name': repo.name,
                'repo_full_name': repo.full_name,
                'member_id': collaborator.id,
                'member_login': collaborator.login,
                'member_name': collaborator.name,
                'permissions': collaborator.permissions,
                'created_at': collaborator.created_at,
            })
    except Exception as ex:
        print(f"Error fetching collaborators for {repo.full_name}: {ex}")

df_repo_members = pd.DataFrame(list_repo_members)
df_repo_members

NamedUser(login="nguyencongluat")
NamedUser(login="tuandq2112")
NamedUser(login="kongyb1032002")
NamedUser(login="MinhPC2k3")
Error fetching collaborators for blcvn/lab-gitlab-api: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/collaborators/collaborators#list-repository-collaborators", "status": "404"}
NamedUser(login="DXL64")
NamedUser(login="kongyb1032002")
NamedUser(login="trananhhh")
NamedUser(login="DXL64")
NamedUser(login="kongyb1032002")
NamedUser(login="kongyb1032002")
NamedUser(login="kongyb1032002")
NamedUser(login="kongyb1032002")
NamedUser(login="dnguyenx215")
NamedUser(login="kongyb1032002")
NamedUser(login="duynguyen1505df")
NamedUser(login="kongyb1032002")
NamedUser(login="kongyb1032002")
NamedUser(login="kongyb1032002")
NamedUser(login="kongyb1032002")
NamedUser(login="kongyb1032002")
NamedUser(login="kongyb1032002")
NamedUser(login="kongyb1032002")
NamedUser(login="kongyb1032002")
NamedUser(login="kongyb1032002")
NamedUser(login="trananhhh")
NamedUser(login="DXL64")
NamedUser(login="kongyb1032002")

,repo_name,repo_full_name,member_id,member_login,member_name,permissions,created_at
0,corev4-explorer,blcvn/corev4-explorer,54891493,nguyencongluat,Nguyễn Công Luật,"Permissions(triage=True, push=True, pull=True,...",2019-09-04 10:37:21+00:00
1,corev4-explorer,blcvn/corev4-explorer,66109626,tuandq2112,tuandq3,"Permissions(triage=True, push=True, pull=True,...",2020-05-29 06:53:53+00:00
2,corev4-explorer,blcvn/corev4-explorer,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
3,corev4-explorer,blcvn/corev4-explorer,99344882,MinhPC2k3,MinhPC,"Permissions(triage=True, push=True, pull=True,...",2022-02-09 15:00:28+00:00
4,CYB-Database,DXL64/CYB-Database,51529680,DXL64,Đặng Xuân Lộc,"Permissions(triage=True, push=True, pull=True,...",2019-06-09 10:33:39+00:00
5,CYB-Database,DXL64/CYB-Database,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
6,CYB-Manager,DXL64/CYB-Manager,32959690,trananhhh,Nguyen Tran Quoc Anh,"Permissions(triage=True, push=True, pull=True,...",2017-10-20 13:22:41+00:00
7,CYB-Manager,DXL64/CYB-Manager,51529680,DXL64,Đặng Xuân Lộc,"Permissions(triage=True, push=True, pull=True,...",2019-06-09 10:33:39+00:00
8,CYB-Manager,DXL64/CYB-Manager,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
9,Ansible_example,kongyb1032002/Ansible_example,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
10,docker-database,kongyb1032002/docker-database,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
11,GoEthExamp,kongyb1032002/GoEthExamp,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
12,go_microservice,kongyb1032002/go_microservice,64138888,dnguyenx215,Duy Nguyen,"Permissions(triage=True, push=True, pull=True,...",2020-04-22 11:07:13+00:00
13,go_microservice,kongyb1032002/go_microservice,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
14,go_microservice,kongyb1032002/go_microservice,162083789,duynguyen1505df,None,"Permissions(triage=True, push=True, pull=True,...",2024-03-04 04:36:54+00:00
15,HAM-Tracking-Tool,kongyb1032002/HAM-Tracking-Tool,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
16,Hyperledger-fabric,kongyb1032002/Hyperledger-fabric,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
17,hyperledger-subscriber,kongyb1032002/hyperledger-subscriber,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
18,L12SQ,kongyb1032002/L12SQ,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
19,lab-api-gitlab,kongyb1032002/lab-api-gitlab,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
20,mmo-frontend,kongyb1032002/mmo-frontend,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
21,NuxtBase,kongyb1032002/NuxtBase,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
22,Solidity,kongyb1032002/Solidity,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
23,VNPAY-Go-Example,kongyb1032002/VNPAY-Go-Example,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00
24,logos-gpt,trananhhh/logos-gpt,32959690,trananhhh,Nguyen Tran Quoc Anh,"Permissions(triage=True, push=True, pull=True,...",2017-10-20 13:22:41+00:00
25,logos-gpt,trananhhh/logos-gpt,51529680,DXL64,Đặng Xuân Lộc,"Permissions(triage=True, push=True, pull=True,...",2019-06-09 10:33:39+00:00
26,logos-gpt,trananhhh/logos-gpt,83600970,kongyb1032002,None,"Permissions(triage=True, push=True, pull=True,...",2021-05-03 16:10:46+00:00

In [32]:
file_repo_members = os.path.join(info_folder, 'repo_members.csv')
df_repo_members.to_csv(file_repo_members, index=False)