In [90]:
from github import Github
import os
import time
import pandas as pd

In [91]:
department = 'BLC'
private_token = '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'
host = "https://github.com"

In [92]:
g = Github(login_or_token=private_token)

# Folder to store export files
info_folder = os.path.join('info', department)
os.makedirs(info_folder, exist_ok=True)

In [93]:
# Lấy các organizations của user
organizations = g.get_user().get_orgs()
list_organizations = []

In [94]:
# Thu thập thông tin các organizations
for org in organizations:
    list_organizations.append({
        'id': org.id,
        'name': org.login,
        'path': org.login,
        'url': org.html_url,
    })

df_organizations = pd.DataFrame(list_organizations)
df_organizations

          id         name         path                             url
0  129816109  blc-onchain  blc-onchain  https://github.com/blc-onchain

In [95]:
# Lưu thông tin các organization vào CSV
file_org = os.path.join(info_folder, 'organization-export.csv')
df_organizations.to_csv(file_org)

In [96]:
# Lấy repository cá nhân của user
user = g.get_user()
personal_repositories = user.get_repos()
list_repositories = []

In [97]:
# List all org
for org in organizations:
    repositories = org.get_repos()
    for repo in repositories:
        # Tách phần tên tổ chức (org) từ full_name
        org_name, repo_name = repo.full_name.rsplit('/', 1)

        # Tạo thư mục cho tổ chức (nếu chưa tồn tại)
        repo_folder = os.path.join(info_folder, org_name)
        os.makedirs(repo_folder, exist_ok=True)

        # Đường dẫn tệp zip repository
        repo_file = os.path.join(repo_folder, f"{repo_name}.zip")

        # URL để tải repository
        repo_url = f"https://github.com/{repo.full_name}/archive/refs/heads/main.zip"  # Giả sử nhánh 'main' là mặc định
        list_repositories.append({
            'id': repo.id,
            'name': repo.name,
            'name_with_namespace': repo.full_name,
            'folder': repo_folder,
            'project_file': repo_file,
            'group': repo.organization.login
        })
        # Dùng curl để tải file về
        os.system(f"curl -L {repo_url} -o {repo_file}")
        print(f"Downloaded {repo_name} to {repo_file}")

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

Downloaded bot-chat-gpt to info/BLC/blc-onchain/bot-chat-gpt.zip

100 65192    0 65192    0     0  56862      0 --:--:--  0:00:01 --:--:-- 56862

In [98]:
# # Thu thập thông tin các repository cá nhân
# for repo in personal_repositories:

#     # Tách phần tên người dùng (user) từ full_name
#     user_name, repo_name = repo.full_name.rsplit('/', 1)

#     # Tạo thư mục cho người dùng (nếu chưa tồn tại)
#     repo_folder = os.path.join(info_folder, user_name)
#     os.makedirs(repo_folder, exist_ok=True)

#     # Đường dẫn tệp zip repository
#     repo_file = os.path.join(repo_folder, f"{repo_name}.zip")

#     # URL để tải repository
#     repo_url = f"https://github.com/{repo.full_name}/archive/refs/heads/main.zip"  # Giả sử nhánh 'main' là mặc định

#     # Dùng curl để tải file về
#     os.system(f"curl -L {repo_url} -o {repo_file}")
#     list_repositories.append({
#         'id': repo.id,
#         'name': repo.name,
#         'name_with_namespace': repo.full_name,
#         'folder': repo_folder,
#         'project_file': repo_file,
#         'group': repo.organization
#     })


#     print(f"Downloaded {repo.organization}/{repo_name} to {repo_file}")

# # Chuyển thông tin repository sang DataFrame

In [99]:
df_repositories = pd.DataFrame(list_repositories)
df_repositories

,id,name,name_with_namespace,folder,project_file,group
0,601876893,bot-chat-gpt,blc-onchain/bot-chat-gpt,info/BLC/blc-onchain,info/BLC/blc-onchain/bot-chat-gpt.zip,blc-onchain

In [100]:
# Lưu thông tin repository vào CSV
file_repo = os.path.join(info_folder, 'repository-export.csv')
df_repositories.to_csv(file_repo)

print("Done exporting GitHub data")

Done exporting GitHub data