In [27]:
pip install -r requirements.txt

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyGithub in /home/ntkong/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.5.0)
Requirement already satisfied: pyjwt[crypto]>=2.4.0 in /home/ntkong/.local/lib/python3.10/site-packages (from PyGithub->-r requirements.txt (line 1)) (2.9.0)
Requirement already satisfied: requests>=2.14.0 in /home/ntkong/.local/lib/python3.10/site-packages (from PyGithub->-r requirements.txt (line 1)) (2.32.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/ntkong/.local/lib/python3.10/site-packages (from PyGithub->-r requirements.txt (line 1)) (4.12.2)
Requirement already satisfied: urllib3>=1.26.0 in /usr/lib/python3/dist-packages (from PyGithub->-r requirements.txt (line 1)) (1.26.5)
Requirement already satisfied: pynacl>=1.4.0 in /usr/lib/python3/dist-packages (from PyGithub->-r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: Deprecated in /home/ntkong/.local/lib/python3.10/site-packages (from PyGithub->-r requirements.txt (line 1)) (1.2.14)
Requirement already satisfied: cryptography>=3.4.0 in /usr/lib/python3/dist-packages (from pyjwt[crypto]>=2.4.0->PyGithub->-r requirements.txt (line 1)) (3.4.8)
Requirement already satisfied: cffi>=1.4.1 in /home/ntkong/.local/lib/python3.10/site-packages (from pynacl>=1.4.0->PyGithub->-r requirements.txt (line 1)) (1.17.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.14.0->PyGithub->-r requirements.txt (line 1)) (3.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/ntkong/.local/lib/python3.10/site-packages (from requests>=2.14.0->PyGithub->-r requirements.txt (line 1)) (3.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.14.0->PyGithub->-r requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: wrapt<2,>=1.10 in /home/ntkong/.local/lib/python3.10/site-packages (from Deprecated->PyGithub->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: pycparser in /home/ntkong/.local/lib/python3.10/site-packages (from cffi>=1.4.1->pynacl>=1.4.0->PyGithub->-r requirements.txt (line 1)) (2.22)
Note: you may need to restart the kernel to use updated packages.

In [28]:
import gitlab
import pandas as pd
import os
import time

In [29]:
department = "BLC"
host = 'http://localhost:10001'
private_token = 'glpat-8AxBfU2Zwhxsi3uAxjxx'
info_folder = os.path.join('info', department)

In [30]:
gl = gitlab.Gitlab(url=host, private_token=private_token)
gl.auth()

/tmp/ipykernel_103646/3625467838.py:2: UserWarning: The base URL in the server response differs from the user-provided base URL (http://localhost:10001 -> http://localhost:8929).
This is usually caused by a misconfigured base URL on your side or a misconfigured external_url on the server side, and can lead to broken pagination and unexpected behavior. If this is intentional, use `keep_base_url=True` when initializing the Gitlab instance to keep the user-provided base URL. (python-gitlab: /tmp/ipykernel_103646/3625467838.py:2)
  gl.auth()

In [31]:
try:
    zgroup = gl.groups.create({'name': department, 'path': department})
except Exception as ex:
    print(ex)
group = gl.groups.get(department)
parent_id = group.id

400: Failed to save group {:path=>["has already been taken"]}

In [32]:
cfg_group_file = f'info/{department}/organization-export.csv'
df_group = pd.read_csv(cfg_group_file, index_col=0)
df_group.head()

          id         name         path                             url
0  129816109  blc-onchain  blc-onchain  https://github.com/blc-onchain

In [ ]:
for index, group in df_group.iterrows():
    print(group['name'])
    group_name = group['name']
    try:
        output = gl.groups.create({
            'name': group_name,
            'path': group_name,
            'parent_id': parent_id,
        })
        print(f"Done create group {group_name}")
    except Exception as ex:
        print(f"Error while importing group {group_name}: {ex}")

blc-onchain

NameError: name 'e' is not defined

In [ ]:
cfg_project_file = 'info/BLC/repository-export.csv'
df_project = pd.read_csv(cfg_project_file, index_col=0)
df_project.head()

,id,name,name_with_namespace,folder,project_file
0,863839707,corev4-explorer,blcvn/corev4-explorer,info/BLC/blcvn,info/BLC/blcvn/corev4-explorer.zip
1,884031925,lab-gitlab-api,blcvn/lab-gitlab-api,info/BLC/blcvn,info/BLC/blcvn/lab-gitlab-api.zip
2,856157805,CYB-Database,DXL64/CYB-Database,info/BLC/DXL64,info/BLC/DXL64/CYB-Database.zip
3,856975972,CYB-Manager,DXL64/CYB-Manager,info/BLC/DXL64,info/BLC/DXL64/CYB-Manager.zip
4,877679995,Ansible_example,kongyb1032002/Ansible_example,info/BLC/kongyb1032002,info/BLC/kongyb1032002/Ansible_example.zip

In [ ]:
group = gl.groups.get(department)
projects = df_project.to_dict('records')

In [ ]:
namespaces = gl.namespaces.list(get_all=True)
list_groups = []
for námespace in namespaces:
   list_groups.append({
         'id': námespace.id,
         # 'name': dgroup.name,
         # 'path': dgroup.path,
         # 'full_name': dgroup.full_name,
         'full_path': námespace.full_path,
         # 'parent_id': dgroup.parent_id,
         # 'created_at': dgroup.created_at,
         # 'organization_id': dgroup.organization_id,
    })
# print(list_groups)
list_groups

[{'id': 1, 'full_path': 'root'}, {'id': 23, 'full_path': 'BLC'}]

In [ ]:
def get_fullpath(name, name_with_namespace):
    # print(name_with_namespace)
    parts = name_with_namespace.split('/')
    parts.pop()
    # print(parts)
    parts.insert(0, name)
    return '/'.join(str(x).strip() for x in parts) 
def get_parent(groups, project_path):
    for group in groups:
        if group['full_path'] == project_path: 
            return group['id']
    return None 

def found_project(project_name_with_namespace):
    try:
      return gl.projects.get(project_name_with_namespace)
    except:
      return None

In [ ]:
for project in projects: 
    project_file = project['project_file']
    project_path = get_fullpath(department, project['name_with_namespace'])
    project_name = project['name']
    print("Start importing project: " + project_name + ", path: " + project_path)
    project_name_with_namespace = project_path + "/" + project_name
    project = found_project(project_name_with_namespace)
    
    if project: 
        print("Project: " + project_name_with_namespace + " exists")
        continue 
    
    parent_id = get_parent(list_groups, project_path)
    if not parent_id: 
        parent_id = group.id  # Default in department group 
        print("Project: " + project_name + " not found parent id ")
    
    print(parent_id)

    try:
        with open(project_file, 'rb') as f:
            output = gl.projects.import_project(
                f,
                path=project_name,
                name=project_name,
                namespace=parent_id,
                override_params={'visibility': 'private'},
            )
        
        project_import = gl.projects.get(output['id'], lazy=True).imports.get()
        
        # Wait until the project import is finished
        while project_import.import_status != 'finished':
            time.sleep(1)
            project_import.refresh()
        
        print("Done importing project: " + project_name)
    except Exception as e:
        print(f"An unexpected error occurred while importing project {project_name}: {e}")

Start importing project: corev4-explorer, path: BLC/blcvn
Project: corev4-explorer not found parent id
23
An unexpected error occurred while importing project corev4-explorer: 400: Project namespace name has already been taken
Start importing project: lab-gitlab-api, path: BLC/blcvn
Project: lab-gitlab-api not found parent id
23

KeyboardInterrupt: